### ISSUE TITLE
401 generating token when using Google Connection 

### ISSUE THREAD

**Issue by schmohlio** [auth0-samples/auth0-golang-web-app#1]
Hi there,

I'm getting 401 on the token `exchange` when using auth0 with Google Connection enabled. Is there someone that can take a look at this functionality? The auth0 logs show a successful api call, but then we receive and error when retrieving the token.

**Comment by chenkie** [comment]
Hey @schmohlio, can you drop an issue into Auth0 support?

**Comment by fardok** [comment]
oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"access_denied","error_description":"Unauthorized"}

I think something wrong with  
  // Exchanging the code for a token
          token, err := conf.Exchange(oauth2.NoContext, code)
          if err != nil {
            http.Error(w, err.Error(), http.StatusInternalServerError)
            return
          }

**Comment by joshes** [comment]
Is there a link to the ticket if one was opened? I'm experiencing this as well ... getting a valid "looking" token, but running it through `https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=<token>` it is indeed invalid.

**Comment by jimmyjames** [comment]
Closing this issue as it is quite old - if you are still experiencing this issue please reopen or create a new issue, including any updated information if applicable.
