### ISSUE TITLE
An example of passing the "state" parameter?

### ISSUE THREAD

**Issue by justinclift** [auth0-samples/auth0-golang-web-app#14]
Trying to pass the state parameter through Auth0, in order to create a proper redirect for users to appropriate page(s) after authentication succeeds.

However, nothing I've tried seems to work.  The "state" parameter doesn't seem to be getting delivered to the callback along with the rest of the info.  The Auth0 docs for this are just a 1 paragraph useless high level mention and no code either. 😦 

Does anyone have this working, with Go?

**Comment by jimmyjames** [comment]
Closing this issue as it is quite old - if you are still experiencing this issue please reopen or create a new issue, including any updated information if applicable.

**Comment by justinclift** [comment]
Well, it hasn't changed.  Is there a way to pass a "next page" or any other kind of variable through the authentication process?

eg so if a person clicked the Login button when they were on page A, they can be returned to page A after the login has completed.

**Comment by justinclift** [comment]
Recreated as #19, as requested.
