### ISSUE TITLE
oauth2: cannot fetch token: 401 Unauthorized

### ISSUE THREAD

**Issue by fardok** [auth0-samples/auth0-golang-web-app#2]
site    syncterest.com

oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"access_denied","error_description":"Unauthorized"}

I think something wrong with  
  // Exchanging the code for a token
          token, err := conf.Exchange(oauth2.NoContext, code)
          if err != nil {
            http.Error(w, err.Error(), http.StatusInternalServerError)
            return
          }

Is it possible to show another examples?  or write worked code without strange  os.Getenv

**Comment by jimmyjames** [comment]
Closing this issue as it is quite old - if you are still experiencing this issue please reopen or create a new issue, including any updated information if applicable.
