### ISSUE TITLE
Failed to verify ID Token: oidc: id token signed with unsupported algorithm, expected ["RS256"] got "HS256"

### ISSUE THREAD

**Issue by Gys** [auth0-samples/auth0-golang-web-app#24]
I get this error when I run the code after downloading. Nothing was changed in the dashboard and nothing in the code. Simply trying an email login.

From searching more general I understand this is probably related to some setting somewhere. 

https://github.com/coreos/go-oidc does not support HS256, so its an Auth0 thing? But I would expect these things all to be correct in a simple demo? Does this mean a simple email login implementation (in Go) is not possible?

**Comment by Gys** [comment]
I found the solution: in the App - Settings there is an advanced section with a OAuth tab giving a dropdown for 'JsonWebToken Signature Algorithm'. This defaults to HS256 and needs to be changed to RS256.

Needs to be in the readme!

**Comment by ylz-at** [comment]
I found that my company openid server uses HS256 but the algo supported by go-oidc is RS256...
