### ISSUE TITLE
Getting a state mismatch on first login attempt

### ISSUE THREAD

**Issue by spacemojo** [auth0-samples/auth0-golang-web-app#33]
I downloaded the sample app from the Auth0 website for the application with which I want to integrate. 
All the values (client id, etc ..) are set correctly and everything builds and starts as expected.
The problem is that on the first login attempt, the state value is not properly stored in the current session thus ending in an error in the callback function when attempting to compare the state in the query parameters with the one in the session that is "". On retry, without closing the tab or browser, it then seems to work correctly.
Ran on MacOS Big Sur (11.1) with Chrome (latest) and Go 1.14

**Comment by jimmyjames** [comment]
Were you able to reproduce this issue with this sample application, without modification? I've not been able to reproduce it locally. If you have made changes, please share them so I can reproduce and better understand what might be going on here. Thanks!
