### ISSUE TITLE
Version in go.mod should be bumped up to 1.18

### ISSUE THREAD

**Issue by jyeager-dusty** [auth0-samples/auth0-golang-web-app#53]
In go.mod, the requested version of go should be:
go 1.18

It is currently:
go 1.16

Currently with the instructions, and without the fix, this is the result of "go run main.go"
# github.com/gin-gonic/gin/render
vendor/github.com/gin-gonic/gin/render/html.go:23:19: undeclared name: any (requires version go1.18 or later)
...

**Comment by sergiught** [comment]
Closing this due to https://github.com/auth0-samples/auth0-golang-web-app/pull/55 having been merged. Thanks for the heads up @jyeager-dusty ! 🙏🏻
